### ISSUE TITLE
"Cannot find module" when running (Debian 9, node 6)

### ISSUE THREAD

**Issue by GameboyRMH** [patrickjquinn/P-Brain.ai-RasPi#9]
I get this error when trying to install and run on a Debian 9 VPS:

`gameboyrmh@vps166142:~/P-Brain.ai-RasPi$ npm install
npm WARN P-Brain.ai-Client@0.5.3 No repository field.
npm WARN P-Brain.ai-Client@0.5.3 license should be a valid SPDX license expression
gameboyrmh@vps166142:~/P-Brain.ai-RasPi$ npm start

> P-Brain.ai-Client@0.5.3 start /home/gameboyrmh/P-Brain.ai-RasPi
> node client.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/home/gameboyrmh/P-Brain.ai-RasPi/node_modules/snowboy/lib/node/binding/Release/node-v48-linux-x64/snowboy.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gameboyrmh/P-Brain.ai-RasPi/node_modules/snowboy/lib/node/index.js:7:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.9.0-5-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! P-Brain.ai-Client@0.5.3 start: `node client.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the P-Brain.ai-Client@0.5.3 start script 'node client.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the P-Brain.ai-Client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node client.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs P-Brain.ai-Client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls P-Brain.ai-Client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gameboyrmh/P-Brain.ai-RasPi/npm-debug.log
gameboyrmh@vps166142:~/P-Brain.ai-RasPi$ ls -la /home/gameboyrmh/P-Brain.ai-RasPi/node_modules/snowboy/lib/node/binding/Release/
total 12
drwxr-xr-x 3 gameboyrmh gameboyrmh 4096 Jan 11 22:15 .
drwxr-xr-x 3 gameboyrmh gameboyrmh 4096 Jan 11 22:15 ..
drwxr-xr-x 2 gameboyrmh gameboyrmh 4096 Jan 11 22:15 node-v48-darwin-x64
gameboyrmh@vps166142:~/P-Brain.ai-RasPi$ 
`

**Comment by patrickjquinn** [comment]
Are you running the set up script first as per the docs? Is the server running that you're trying to connect the client to? Have you tried manually installing the module snowboy?

**Comment by GameboyRMH** [comment]
I followed the Debian/Ubuntu install instructions. The server wasn't running at the time, but I've tried again with the server running and had the same result. The server works with the Android client. I also tried "npm install --save snowboy" and had the same result afterward, not sure if there are other steps I need to take though.

**Comment by patrickjquinn** [comment]
Okay i’ll investigate on monday, this client needs a re-write as it hasn’t been updated in a while.

Kind Regards,

Patrick Quinn.
